name: Merge from localstorage to main
on:
  push:
    branches:
      - 'localstorage'
jobs:
  sync-branch-localstorage:
    runs-on: ubuntu-latest
    #    // https://github.com/devmasx/merge-branch/issues/34
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master

      - name: Merge localstorage -> main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: localstorage
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
