---
title: Suggestions state diagram
---
stateDiagram-v2
%%    s2 : This is a state description
    [*] --> NEW
    [*] --> NOTIFICATION
%%    Still --> [*]

    NEW --> DECIDE_LATER: click on 'later'
    NEW --> CHECKED: click on 'check'
    DECIDE_LATER --> DECIDE_LATER
    DECIDE_LATER --> IGNORED
    DECIDE_LATER --> CHECKED
    NOTIFICATION --> IGNORED
    NOTIFICATION --> CHECKED
    NEW --> IGNORED
