### GET
HEAD https://www.chefkoch.de/rezepte/1338991238751459/Knusprige-Bratkartoffeln-nach-Muttis-Rezept.html

### GET
GET https://rss.reddit.com/r/rss/comments/14c4p42/feed_reader_that_supports_reddit_comments/


### GET2
HEAD https://www.dkb.de/banking

### Send POST request with json body
POST https://us-central1-tabsets-dev.cloudfunctions.net/app/hf/categorization
Content-Type: application/json

{
}

### Send POST request with json body
POST https://us-central1-tabsets-dev.cloudfunctions.net/app/hf/classify?text=I%20love%20Transformers.js
Content-Type: application/json

{
}

###
GET https://us-central1-tabsets-dev.cloudfunctions.net/app/share/preview/0d2ec1f2-e829-4652-b9de-eb1bd5df7665?n=cGZsYW56a/xiZWw=&a=Q2Fyc3Rlbg==

###
GET https://tabsets-dev.web.app/share/preview/0d2ec1f2-e829-4652-b9de-eb1bd5df7665?n=cGZsYW56a/xiZWw=&a=Q2Fyc3Rlbg==

###
GET https://tabsets-dev.firebaseapp.com/app/share/preview/0d2ec1f2-e829-4652-b9de-eb1bd5df7665?n=cGZsYW56a/xiZWw=&a=Q2Fyc3Rlbg==

###
GET https://us-central1-tabsets-dev.cloudfunctions.net/app/share/img/0d2ec1f2-e829-4652-b9de-eb1bd5df7665

###
GET https://tabsets-72089.web.app/share/preview/9dec3763-b499-405e-81d9-108e2fd5d2da?n=SW5mcmFzdHJ1Y3R1cmU=&a=Q2Fyc3Rlbg==
