name: 'coverage'
on:
#  pull_request:
#    branches:
#      - master
#      - main
  push:
    branches: [ main, chrome-extension,vitest,TAB-** ]
jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Install Deps'
        run: yarn install
      - name: 'Test'
        run: npx vitest --coverage
      - name: 'Report Coverage'
        if: always() # Also generate the report if tests are failing
        uses:  davelosert/vitest-coverage-report-action@v2

      - run: npm run "build bex (publish)"
      - run: npx playwright install
      - run: npm run test:e2e
      - uses: actions/upload-artifact@v4
#        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
