name: 'build'
on:
#  pull_request:
#    branches:
#      - master
#      - main
  push:
    branches: [ main ]
jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Create env file'
        run: |
          touch .env
          echo STAGE=PRD >> .env
          echo TABSETS_PWA_URL="https://pwa.tabsets.net" >> .env
          echo SENTRY_PROJECT_NAME="tabsets" >> .env
          echo SENTRY_DSN="${{ secrets.SENTRY_DNS }}" >> .env
          echo HOST="chrome.extension" >> .env
          echo LOCALE="en" >> .env
      - name: 'Install Deps'
        run: yarn install
      - name: 'Test'
        run: npx vitest --coverage
      - name: 'Report Coverage'
        if: always() # Also generate the report if tests are failing
        uses:  davelosert/vitest-coverage-report-action@v2

      - run: npm run "build bex (publish)"
#      - uses: actions/upload-artifact@v4
#        with:
#          name: playwright-report
#          path: playwright-report/
#          retention-days: 30
