name: Node.js CI
run-name: E2E Tests
on:
  push:
    branches: [ main, chrome-extension ]
  pull_request:
    branches: [ main, chrome-extension ]

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.44.1-jammy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Run your tests
        run: xvfb-run npx playwright test
        env:
          HOME: /root
