name: Publish
on:
  push:
    tags:
      - 'v*.*.*-edge'
jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: 'Create env file'
        run: |
          touch .env
          echo STAGE=PRD >> .env
          echo LOCALE="en" >> .env
          echo TABSETS_PWA_URL="https://pwa.tabsets.net" >> .env
          echo SENTRY_PROJECT_NAME="tabsets" >> .env
          echo SENTRY_DSN="${{ secrets.SENTRY_DNS }}" >> .env
          echo HOST="edge.extension" >> .env
          echo GRAFANA_LOKI_USER="1188330" >> .env
          echo GRAFANA_METRICS_USER="2385306" >> .env
          echo GRAFANA_LOKI_TOKEN="${{ secrets.GRAFANA_LOKI_TOKEN }}" >> .env
          echo GRAFANA_METRICS_KEY="${{ secrets.GRAFANA_METRICS_KEY }}" >> .env
          echo GRAFANA_FARO_COLLECTOR_URL="https://faro-collector-prod-eu-west-2.grafana.net/collect/937ed141737572b1e1823cfbe9895c7b" >> .env
      - name: Build
        run: |
          yarn install
          npm run "build bex chrome"
      - uses: wdzeng/edge-addon@v2
        name: "Upload and release"
        with:
          product-id: "d5d382d8-4033-4559-a15a-c12e8a9f64e0"
          zip-path: dist/bex-chrome/Packaged.tabsets.net.zip
          api-key: ${{ secrets.EDGE_API_KEY }}
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          upload-only: true
