name: Publish
on:
  push:
    branches: [ chrome-extension ]
  #pull_request:
  #  branches: [ chrome-extension ]

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: 'true'
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: 'Create env file'
        run: |
          touch .env
          echo STAGE=PRD >> .env
          echo FIREBASE_ACTIVE=false >> .env
          echo BACKEND_URL="https://tabsets-72089.web.app" >> .env
          echo TABSETS_PWA_URL="https://pwa.tabsets.net" >> .env
          echo FIREBASE_API_KEY="${{ secrets.FIREBASE_API_KEY }}" >> .env
          echo FIREBASE_AUTH_DOMAIN="tabsets-72089.firebaseapp.com" >> .env
          echo FIREBASE_PROJECT_ID="tabsets-72089" >> .env
          echo FIREBASE_APP_ID="${{ secrets.FIREBASE_APP_ID }}" >> .env
          echo FIREBASE_MESSAGING_SENDER_ID="${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo FIREBASE_STORAGE_BUCKET="tabsets-72089.appspot.com" >> .env
          echo FIREBASE_DATABASE_URL="${{ secrets.FIREBASE_DATABASE_URL }}" >> .env
          echo FIREBASE_MESSAGING_KEY="${{ secrets.FIREBASE_MESSAGING_KEY }}" >> .env
      - name: Build
        run: |
          yarn install
          npm run "build bex (publish)"
      - name: Upload & release
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: dist/bex/Packaged.tabsets.net.zip
          extension-id: afkknkdbgondbbfjehipnjmojndnjhjg
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          publish: false
