name: Sync multiple branches
on:
  push:
    branches:
      - 'chrome-extension'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge chrome-extension -> firefox-extension
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: chrome-extension
          target_branch: firefox-extension
          github_token: ${{ secrets.GITHUB_TOKEN }}
